version: "3.8"

services:
  order-api:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      PORT: 3001
      DATABASE_URL: ${DATABASE_URL}
      KITCHEN_API_URL: ${KITCHEN_API_URL}
      NOTIFICATION_API_URL: ${NOTIFICATION_API_URL}
    networks:
      - shoong-network

networks:
  shoong-network:
    external: true